Product.create!([
  {name: "Name", price: "5904116.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "30448345.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "7465905.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "13329182.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "13597518.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "45835296.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "45471299.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "44997927.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "27809871.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "16015676.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "39148710.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "2574172.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "10867840.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "44898141.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "11514023.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "36611528.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "32452664.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "18451445.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "13191087.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "37977617.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "8177717.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "38029706.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "12096581.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "26250891.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "44255912.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "6412912.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "24066151.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "7283137.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "26954533.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "886438.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "34875053.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "37645830.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "15832744.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "33107415.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "26685773.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "16570944.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "40167010.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "5247995.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "1056027.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "11823512.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "15999174.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "21073881.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "22628073.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "6359552.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "25414122.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "44417477.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "11556913.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "49990556.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "37672674.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "47605035.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "37921222.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "46631342.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "34752516.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "903570.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "11529822.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "39823154.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "33025774.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "23756816.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "8021791.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "44555051.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "3336944.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "44454861.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "43686411.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "40201513.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "22103929.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "7627669.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "18962276.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "45441446.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "23512407.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "33819722.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "49821155.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "4476398.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "37437198.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "10831570.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "22213740.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "45500921.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "48449040.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "28821793.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "45453144.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "4540204.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "23774506.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "34332641.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "29692623.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "37698917.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "1216081.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "4826121.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "45283219.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "24117261.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "34293597.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "23964263.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "29457053.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "4407381.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "38463186.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "26512136.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "13053431.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "Name", price: "25094345.0", image_url: "https/for now boring", description: "Descriiption", in_stock: false},
  {name: "post name", price: "19065775.0", image_url: "post image_url", description: "post description", in_stock: false},
  {name: nil, price: "39829945.0", image_url: nil, description: nil, in_stock: false},
  {name: "a", price: "46561339.0", image_url: "a", description: "a", in_stock: false},
  {name: "a", price: "24228461.0", image_url: "a", description: "a", in_stock: false},
  {name: "dan", price: "30699218.0", image_url: "a", description: "d", in_stock: false},
  {name: "josh", price: "43804269.0", image_url: "ads", description: "asdf", in_stock: false},
  {name: "Zipora", price: "25276654.0", image_url: "dffg", description: "dfsg", in_stock: false},
  {name: "new", price: "10.1", image_url: "dfssa", description: "dsaf", in_stock: true},
  {name: "new", price: "134123.13", image_url: "sdfasd", description: "dsaf", in_stock: true}
])
